#
# Default makefile to manipulate package repo
#

.PHONY : info
helm\:info:
	@echo "REPO_URL: $(REPO_URL)"

.PHONY : index
helm\:index:
	@echo "## Generating index for $(REPO_URL)"
	@helm repo index . --url $(REPO_URL) --debug

.PHONY : clean
helm\:clean:
	@rm -f index.yaml *.tgz
