#
# Default makefile to manipulate package repo
#

.PHONY : info
info:
	@echo "REPO_URL: $(REPO_URL)"

.PHONY : index
index:
	@echo "## Generating index for $(REPO_URL)"
	@helm repo index . --url $(REPO_URL) --debug

.PHONY : real-clean
real-clean: clean
	rm -f *.tgz

.PHONY : clean
clean:
	rm -f index.yaml
