export REPO_URL := $(REPO_URL)/$(shell basename $(CURDIR))

.PHONY : info
info:
	@make -C packages/ $@

.PHONY : package
package:
	 find library/ -type d -d 1 '!' -name packages | xargs helm package
	 find . -type f -name '*.tgz' -d 1 | xargs -I '{}' mv {} packages

.PHONY : index
index:
	@make -C packages/ $@

.PHONY : clean
clean:
	@rm -f *.tgz
  
.PHONY : real-clean
real-clean: clean
	@make -C packages/ $@
